spring.application.name=MSProject_06_CircuitBreaker

resilience4j.circuitbreaker.instances.ticketService.sliding-window-size=5
resilience4j.circuitbreaker.instances.ticketService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.ticketService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.ticketService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.ticketService.permitted-number-of-calls-in-half-open-state=1