spring.application.name=ConfigurationProperties_Annotation_03

student.info.id = 40
student.info.name = Saikumar Laveti
student.info.gender = Male


emp.info.id=1
emp.info.name=Santosh Kumar

#person details

per.info.id=1
per.info.name = SAIKUMAR LAVETI

#fav colors - array
per.info.favColors[0] = Black
per.info.favColors[1] = Green
per.info.favColors[2] = Red

#studies = list
per.info.studies[0] = Degree
per.info.studies[1] = MCA

#phone number = set
per.info.phoneNumbers[0] = 7995663051
per.info.phoneNumbers[1] = 8501905061

#ids - proofs -map
per.info.idProofs.aadharNumber=12345
per.info.idProofs.voterId=40

per.info.std.id = 1
per.info.std.name = Santosh
per.info.std.gender = Male