spring.application.name=MSProject_04_EmployeeService

server.port=9900
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# if config server is in default port 8888
#spring.config.import=optional:configserver:

spring.config.import=optional:configserver:http://localhost:8888