spring.application.name=SpringRestProject_01_FirstProviderApp

server.port=8081
server.servlet.context-path=/RestApp
#if the run the application through External server tomcat this is the URL
#http://localhost:8080/SpringRestProject_01_FirstProviderApp/messageApi/wish

#if the run the application through SpringBoot this is the URL
#http://localhost:8081/RestApp/messageApi/wish

#GetMapping - http://localhost:8081/RestApp/emp/api/getEmployee
#PostMapping - http://localhost:8081/RestApp/emp/api/save
#PutMapping - http://localhost:8081/RestApp/emp/api/update
#PatchMapping - http://localhost:8081/RestApp/emp/api/updateName