home.title=Welcome to Spring Boot MVC
home.link=Register Customer

cust.registration.title=Customer Registration
cust.registration.name=Customer Name
cust.registration.address=Customer Address
cust.registration.billAmt=Customer Bill Amount

cust.btn.register=Register