spring.application.name=MSProject_05_SpringActuatorsInfo

info.app.name=CUST-Service info
info.app.version=2.0
info.app.description=SpringActuatorsInfo
info.app.createdBy=Team-Saikumar
server.port=8081
management.endpoint.info.enabled=true
management.endpoints.web.exposure.include=*
management.info.env.enabled=true

#http://localhost:8081/actuator/beans
#http://localhost:8081/actuator/configprops
#http://localhost:8081/actuator/env
#http://localhost:8081/actuator/loggers
#http://localhost:8081/actuator/scheduledtasks
#http://localhost:8081/actuator/threaddump
#http://localhost:8081/actuator/mappings
#http://localhost:8081/actuator/heapdemp
#http://localhost:8081/actuator/caches
#http://localhost:8081/actuator/metrics