spring.application.name=SpringMVCStudent_CRUD_Project

server.port=5052
spring.mvc.view.prefix=/Pages/
spring.mvc.view.suffix=.jsp 

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/student
spring.datasource.username=root
spring.datasource.password=pass1234

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

logging.level.org.springframework.web.servlet.view=DEBUG