spring.application.name=MSProject_07_LoggingAndTracing

server.port=9091

logging.file.name=D:/Spring_Revision/Logs/MSProject_07.log

management.tracing.sampling.probability=1.0

management.tracing.export.zipkin.endpoint=http://127.0.0.1:9411/api/v2/spans