spring.application.name=SpringBatchRealTimeExample

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/student
spring.datasource.username=root
spring.datasource.password=pass1234

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Spring Batch metadata tables
spring.batch.jdbc.initialize-schema=always

# Run batch job automatically when application starts
spring.batch.job.enabled=true